/* eslint-env browser*/
window.onload = function () {
    var context = { Teams:
   [ { 'Team Number': 'Team 1',
       'Team Lead': 'Sam McGrath',
       'Assistant Lead': 'Juan Alvarez',
       'Work Hours': '8:00 - 11:00 AM',
       TeamMembers:
        [ { 'Student Name': 'Juan Alvarez',
            Courses:
             [ { 'Course Code': 'GS 120 - G', Department: 'General Studies' },
               { 'Course Code': 'GS 120L - G', Department: 'General Studies' } ] },
          { 'Student Name': 'Hannah Spear',
            Courses:
             [ { 'Course Code': 'B 183', Department: 'Business Management' },
               { 'Course Code': 'B 283', Department: 'Business Management' },
               { 'Course Code': 'B 201', Department: 'Business Management' },
               { 'Course Code': 'B 211', Department: 'Business Management' },
               { 'Course Code': 'B 380', Department: 'Business Management' },
               { 'Course Code': 'CHEM 101', Department: 'Chemistry' },
               { 'Course Code': 'CHEM 101L', Department: 'Chemistry' },
               { 'Course Code': 'COMM 102', Department: 'Communication' },
               { 'Course Code': 'COMM 450', Department: 'Communication' } ] },
          { 'Student Name': 'Jason Braithwaite',
            Courses:
             [ { 'Course Code': 'ENG 335', Department: 'English' },
               { 'Course Code': 'ENG 332', Department: 'English' },
               { 'Course Code': 'FDENG 101', Department: 'English' },
               { 'Course Code': 'ENG 252', Department: 'English' },
               { 'Course Code': 'ENG 355', Department: 'English' },
               { 'Course Code': 'ENG 106 - G', Department: 'English' },
               { 'Course Code': 'ENG 106 - NG', Department: 'English' },
               { 'Course Code': 'ENG 325', Department: 'English' },
               { 'Course Code': 'ENG 314', Department: 'English' } ] },
          { 'Student Name': 'Emily Galbraith',
            Courses:
             [ { 'Course Code': 'FHGEN 211',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 212',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 251A',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 251B',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 251C',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 251D',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 252A',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 252B',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 252C',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 252D',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 270',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 399',
                 Department: 'Interdiscip Studies' } ] },
          { 'Student Name': 'Katy Kempton',
            Courses:
             [ { 'Course Code': 'FHGEN 130',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 140',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 160',
                 Department: 'Interdiscip Studies' } ] },
          { 'Student Name': 'Jonathan Manoa',
            Courses:
             [ { 'Course Code': 'MATH 100G - G', Department: 'Mathematics' },
               { 'Course Code': 'MATH 100L - G', Department: 'Mathematics' } ] },
          { 'Student Name': 'Cole Herrin',
            Courses:
             [ { 'Course Code': 'B 370', Department: 'Business Management' },
               { 'Course Code': 'B 424', Department: 'Business Management' },
               { 'Course Code': 'B 424D', Department: 'Business Management' },
               { 'Course Code': 'B 448', Department: 'Business Management' },
               { 'Course Code': 'B 129', Department: 'Business Management' },
               { 'Course Code': 'B 215', Department: 'Business Management' },
               { 'Course Code': 'CIT 380',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CIT 381',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CIT 261',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CIT 360',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'ME 201',
                 Department: 'Mechanical Engineering' },
               { 'Course Code': 'AUTO 125',
                 Department: 'Mechanical Engineering' },
               { 'Course Code': 'ME 202',
                 Department: 'Mechanical Engineering' },
               { 'Course Code': 'ME 231',
                 Department: 'Mechanical Engineering' },
               { 'Course Code': 'ME 172',
                 Department: 'Mechanical Engineering' },
               { 'Course Code': 'MATH 221A', Department: 'Mathematics' },
               { 'Course Code': 'MATH 221B', Department: 'Mathematics' },
               { 'Course Code': 'MATH 221C', Department: 'Mathematics' },
               { 'Course Code': 'FDMAT 112', Department: 'Mathematics' },
               { 'Course Code': 'MATH 100B', Department: 'Mathematics' },
               { 'Course Code': 'FDWLD 101', Department: 'Foundations' },
               { 'Course Code': 'FDWLD 201', Department: 'Foundations' } ] },
          { 'Student Name': 'Seth Childers',
            Courses:
             [ { 'Course Code': 'COMM 150', Department: 'Communication' },
               { 'Course Code': 'COMM 175', Department: 'Communication' },
               { 'Course Code': 'COMM 250', Department: 'Communication' },
               { 'Course Code': 'COMM 273', Department: 'Communication' },
               { 'Course Code': 'COMM 125', Department: 'Communication' },
               { 'Course Code': 'COMM 130', Department: 'Communication' },
               { 'Course Code': 'COMM 307', Department: 'Communication' },
               { 'Course Code': 'COMM 352', Department: 'Communication' },
               { 'Course Code': 'COMM 310', Department: 'Communication' },
               { 'Course Code': 'COMM 289', Department: 'Communication' },
               { 'Course Code': 'COMM 111', Department: 'Communication' },
               { 'Course Code': 'COMM 497R - Block 1',
                 Department: 'Communication' },
               { 'Course Code': 'COMM 315', Department: 'Communication' },
               { 'Course Code': 'COMM 280', Department: 'Communication' },
               { 'Course Code': 'FDREL 110 - Block 1', Department: 'Religion' },
               { 'Course Code': 'FDREL 110 - Block 2', Department: 'Religion' },
               { 'Course Code': 'FAML 498R', Department: 'Family' } ] } ] },
     { 'Team Number': 'Team 2',
       'Team Lead': 'Matthew Jones',
       'Assistant Lead': 'Johnna Franks',
       'Work Hours': '11:00 AM - 2:00 PM',
       TeamMembers:
        [ { 'Student Name': 'Johnna Franks',
            Courses:
             [ { 'Course Code': 'SOC 311',
                 Department: 'Sociology & Social Work' },
               { 'Course Code': 'SOC 111',
                 Department: 'Sociology & Social Work' },
               { 'Course Code': 'SOC 323',
                 Department: 'Sociology & Social Work' },
               { 'Course Code': 'ANTH 101',
                 Department: 'Sociology & Social Work' },
               { 'Course Code': 'SOC 112',
                 Department: 'Sociology & Social Work' },
               { 'Course Code': 'SW 260',
                 Department: 'Sociology & Social Work' },
               { 'Course Code': 'ED 312', Department: 'Teacher Education' },
               { 'Course Code': 'SPED 200', Department: 'Teacher Education' },
               { 'Course Code': 'SPED 441', Department: 'Teacher Education' },
               { 'Course Code': 'ED 200', Department: 'Teacher Education' },
               { 'Course Code': 'ED 202', Department: 'Teacher Education' },
               { 'Course Code': 'SPED 310', Department: 'Teacher Education' } ] },
          { 'Student Name': 'Laikin Guthrie',
            Courses:
             [ { 'Course Code': 'FDREL 130 - Block 1',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 200',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 200 - G',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 121 - G',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 225',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 250',
                 Department: 'Religious Education' },
               { 'Course Code': 'B 475', Department: 'Business' } ] },
          { 'Student Name': 'Matt Wyndham',
            Courses:
             [ { 'Course Code': 'FDINT 211', Department: 'Foundations' },
               { 'Course Code': 'FDHUM 110', Department: 'Foundations' } ] },
          { 'Student Name': 'Katie Pugh',
            Courses:
             [ { 'Course Code': 'FAML 430', Department: 'Home & Family' },
               { 'Course Code': 'FCS 101', Department: 'Home & Family' },
               { 'Course Code': 'FAML 300', Department: 'Home & Family' },
               { 'Course Code': 'FAML 445', Department: 'Home & Family' },
               { 'Course Code': 'FAML 150 - Block 1',
                 Department: 'Home & Family' },
               { 'Course Code': 'FAML 150 - Block 2',
                 Department: 'Home & Family' },
               { 'Course Code': 'FAML 400', Department: 'Home & Family' },
               { 'Course Code': 'FAML 100', Department: 'Home & Family' } ] },
          { 'Student Name': 'Travis Woodbury',
            Courses:
             [ { 'Course Code': 'B 120', Department: 'Business Management' },
               { 'Course Code': 'B 250', Department: 'Business Management' },
               { 'Course Code': 'B 383', Department: 'Business Management' },
               { 'Course Code': 'B 101', Department: 'Business Management' },
               { 'Course Code': 'PSYCH 111', Department: 'Psychology' },
               { 'Course Code': 'NURS 340', Department: 'Nursing' },
               { 'Course Code': 'NURS 400', Department: 'Nursing' } ] },
          { 'Student Name': 'JJ Aragon',
            Courses:
             [ { 'Course Code': 'CIT 352',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CIT 353',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CIT 336',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CIT 110',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'WDD 100',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CIT 301C',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CIT 230',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CS 165', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'CS 246', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'CS 313', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'CS 308', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'ECEN 150', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'CS 124', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'CS 432', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'CS 364', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'HS 390',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 401',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 420',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 460',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'MA 106',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'MA 107',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'MA 111',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'MA 205',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'MATH 111', Department: 'Mathematics' },
               { 'Course Code': 'MATH 111 - Block 1',
                 Department: 'Mathematics' },
               { 'Course Code': 'MATH 109', Department: 'Mathematics' } ] } ] },
     { 'Team Number': 'Team 3',
       'Team Lead': 'Scott Terry',
       'Assistant Lead': 'Sara Balter',
       'Work Hours': '2:00 PM - 5:00 PM',
       TeamMembers:
        [ { 'Student Name': 'Sara Balter',
            Courses:
             [ { 'Course Code': 'FDREL 275',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 301',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 302',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 261',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 324',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 325',
                 Department: 'Religious Education' } ] },
          { 'Student Name': 'Ashley Sayre',
            Courses:
             [ { 'Course Code': 'BIO 264L', Department: 'Biology' },
               { 'Course Code': 'BIO 265L', Department: 'Biology' },
               { 'Course Code': 'BIO 381', Department: 'Biology' },
               { 'Course Code': 'BIO 375', Department: 'Biology' },
               { 'Course Code': 'BIO 264', Department: 'Biology' },
               { 'Course Code': 'BIO 265', Department: 'Biology' } ] },
          { 'Student Name': 'Ethan Koopman',
            Courses:
             [ { 'Course Code': 'FDSCI 205', Department: 'Foundations' },
               { 'Course Code': 'FDAMF 101', Department: 'Foundations' },
               { 'Course Code': 'FDSCI 101', Department: 'Foundations' } ] },
          { 'Student Name': 'Richlue Kpakor',
            Courses:
             [ { 'Course Code': 'ESS 375',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 320',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'RM 307',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 280',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 310',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 285',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 375',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 378',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 425',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 345',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 465',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'RM 370',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'RM 371',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'B 428', Department: 'Business Management' },
               { 'Course Code': 'B 240', Department: 'Business Management' },
               { 'Course Code': 'B 275', Department: 'Business Management' } ] },
          { 'Student Name': 'Seth Benson',
            Courses:
             [ { 'Course Code': 'CS 213', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'CS 235', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'CS 371', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'CS 416', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'CS 470', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'ECEN 160', Department: 'Computer Sci & Eng' },
               { 'Course Code': 'CONST 320',
                 Department: 'Design & Const Mgmt' },
               { 'Course Code': 'ECON 151', Department: 'Economics' },
               { 'Course Code': 'ECON 150', Department: 'Economics' },
               { 'Course Code': 'AGBUS 105', Department: 'Economics' },
               { 'Course Code': 'AGBUS 180A', Department: 'Economics' },
               { 'Course Code': 'AGBUS 180B', Department: 'Economics' },
               { 'Course Code': 'SMM 140', Department: 'None Listed' },
               { 'Course Code': 'TA 116', Department: 'Theatre and Dance' },
               { 'Course Code': 'TA 402', Department: 'Theatre and Dance' } ] } ] },
     { 'Team Number': 'Team 4',
       'Team Lead': 'Austin Swenson',
       'Assistant Lead': 'Mackenzy Taylor',
       'Work Hours': '5:00 PM - 8:00 PM',
       TeamMembers:
        [ { 'Student Name': 'Mackenzy Taylor',
            Courses:
             [ { 'Course Code': 'ART 337R', Department: 'Art' },
               { 'Course Code': 'ART 107', Department: 'Art' },
               { 'Course Code': 'ART 110', Department: 'Art' },
               { 'Course Code': 'ART 331R', Department: 'Art' },
               { 'Course Code': 'FDSCI 201', Department: 'Foundations' } ] },
          { 'Student Name': 'Michael Hardy',
            Courses:
             [ { 'Course Code': 'ART 160', Department: 'Art' },
               { 'Course Code': 'ART 230', Department: 'Art' },
               { 'Course Code': 'ART 235', Department: 'Art' },
               { 'Course Code': 'ART 130', Department: 'Art' },
               { 'Course Code': 'CIT 225',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CIT 262',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CIT 325',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'NURS 338', Department: 'Nursing' },
               { 'Course Code': 'NURS 316', Department: 'Nursing' },
               { 'Course Code': 'NURS 449', Department: 'Nursing' },
               { 'Course Code': 'NURS 450', Department: 'Nursing' },
               { 'Course Code': 'ACCTG 180', Department: 'Accounting' },
               { 'Course Code': 'ACCTG 201', Department: 'Accounting' },
               { 'Course Code': 'NUTR 150',
                 Department: 'Animal & Food Science' },
               { 'Course Code': 'NUTR 200',
                 Department: 'Animal & Food Science' } ] },
          { 'Student Name': 'Emily Jones',
            Courses:
             [ { 'Course Code': 'HS 240',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 370',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 480',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'SPAN 101',
                 Department: 'Lang & Intnl Studies' },
               { 'Course Code': 'SPAN 102',
                 Department: 'Lang & Intnl Studies' },
               { 'Course Code': 'SPAN 302',
                 Department: 'Lang & Intnl Studies' },
               { 'Course Code': 'TESOL 102',
                 Department: 'Lang & Intnl Studies' },
               { 'Course Code': 'TESOL 101',
                 Department: 'Lang & Intnl Studies' },
               { 'Course Code': 'TESOL 104',
                 Department: 'Lang & Intnl Studies' },
               { 'Course Code': 'TESOL 103',
                 Department: 'Lang & Intnl Studies' },
               { 'Course Code': 'TESOL 105',
                 Department: 'Lang & Intnl Studies' },
               { 'Course Code': 'LR 111 - Block 1', Department: 'Library' },
               { 'Course Code': 'LR 111 - Block 2', Department: 'Library' } ] },
          { 'Student Name': 'Kyle Moore',
            Courses:
             [ { 'Course Code': 'PSYCH 201', Department: 'Psychology' },
               { 'Course Code': 'PSYCH 302', Department: 'Psychology' },
               { 'Course Code': 'PSYCH 112', Department: 'Psychology' },
               { 'Course Code': 'PSYCH 311', Department: 'Psychology' },
               { 'Course Code': 'PH 105', Department: 'Physics' },
               { 'Course Code': 'PH 121', Department: 'Physics' },
               { 'Course Code': 'ECI 001',
                 Department: 'Languages & Internationa' },
               { 'Course Code': 'ECI 002',
                 Department: 'Languages & Internationa' },
               { 'Course Code': 'ACCTG 205', Department: 'Accounting' },
               { 'Course Code': 'ACCTG 202', Department: 'Accounting' } ] },
          { 'Student Name': 'Casey Robinson',
            Courses:
             [ { 'Course Code': 'BIO 221', Department: 'Biology' },
               { 'Course Code': 'BIO 230', Department: 'Biology' },
               { 'Course Code': 'BIO 475', Department: 'Biology' },
               { 'Course Code': 'B 321', Department: 'Business Management' },
               { 'Course Code': 'CIT 160',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CIT 260',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CIT 270',
                 Department: 'Computer Info Technology' },
               { 'Course Code': 'CIT 111',
                 Department: 'Computer Info Technology' } ] },
          { 'Student Name': 'Felipe Chora Chavez',
            Courses:
             [ { 'Course Code': 'B 361', Department: 'Business Management' },
               { 'Course Code': 'B 483', Department: 'Business Management' },
               { 'Course Code': 'B 341', Department: 'Business Management' },
               { 'Course Code': 'FDSCI 203', Department: 'Foundations' } ] },
          { 'Student Name': 'Meghan Cottam',
            Courses:
             [ { 'Course Code': 'ENG 106L - G', Department: 'English' },
               { 'Course Code': 'ENG 107', Department: 'English' },
               { 'Course Code': 'ENG 251', Department: 'English' },
               { 'Course Code': 'FDENG 301', Department: 'English' } ] } ] },
     { 'Team Number': 'Full-Time Team',
       'Team Lead': 'Scott O\'Neal',
       'Assistant Lead': 'Johanna Franks',
       'Work Hours': '8:00 AM - 5:00 PM',
       TeamMembers:
        [ { 'Student Name': 'Scott O\'Neal',
            Courses:
             [ { 'Course Code': 'GS 101', Department: 'General Studies' },
               { 'Course Code': 'GS 294', Department: 'General Studies' },
               { 'Course Code': 'GS 111 - Block 1',
                 Department: 'General Studies' },
               { 'Course Code': 'GS 111 - Block 2',
                 Department: 'General Studies' },
               { 'Course Code': 'GS 105', Department: 'General Studies' },
               { 'Course Code': 'GEOL 111', Department: 'Geology' },
               { 'Course Code': 'RM 304',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'HS 391',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'RM 373R',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'RM 471',
                 Department: 'Health Rec & Human Pfrm' } ] },
          { 'Student Name': 'Anne Chambers',
            Courses:
             [ { 'Course Code': 'B 301', Department: 'Business Management' },
               { 'Course Code': 'B 410', Department: 'Business Management' },
               { 'Course Code': 'B 433', Department: 'Business Management' },
               { 'Course Code': 'B 320', Department: 'Business Management' },
               { 'Course Code': 'B 100', Department: 'Business Management' },
               { 'Course Code': 'POLSC 170',
                 Department: 'Hist Geog & PoliSci' },
               { 'Course Code': 'POLSC 150',
                 Department: 'Hist Geog & PoliSci' },
               { 'Course Code': 'POLSC 110',
                 Department: 'Hist Geog & PoliSci' } ] },
          { 'Student Name': 'Nate Hjorth',
            Courses:
             [ { 'Course Code': 'FDMAT 108', Department: 'Mathematics' },
               { 'Course Code': 'FDMAT 215', Department: 'Mathematics' },
               { 'Course Code': 'HRHP 131',
                 Department: 'Health Rec & Human Pfrm' },
               { 'Course Code': 'CONST 380', Department: 'Construction' },
               { 'Course Code': 'FDREL 121',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 122',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 212',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 212 - Block 2',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 211',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 211 - Block 2',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 333',
                 Department: 'Religious Education' },
               { 'Course Code': 'FDREL 250 - NG',
                 Department: 'Religious Education' } ] },
          { 'Student Name': 'Ashwini Krishnan',
            Courses:
             [ { 'Course Code': 'FAML 360', Department: 'Home & Family' },
               { 'Course Code': 'FAML 160', Department: 'Home & Family' },
               { 'Course Code': 'CHILD 320', Department: 'Home & Family' },
               { 'Course Code': 'FCS 340', Department: 'Home & Family' },
               { 'Course Code': 'CHILD 300', Department: 'Home & Family' },
               { 'Course Code': 'CHILD 310', Department: 'Home & Family' },
               { 'Course Code': 'CHILD 210', Department: 'Home & Family' },
               { 'Course Code': 'FAML 220', Department: 'Home & Family' },
               { 'Course Code': 'FAML 460', Department: 'Home & Family' },
               { 'Course Code': 'FAML 200', Department: 'Home & Family' },
               { 'Course Code': 'FHGEN 111',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 112',
                 Department: 'Interdiscip Studies' },
               { 'Course Code': 'FHGEN 120',
                 Department: 'Interdiscip Studies' } ] } ] } ] }
    
    var teamsTemplate = $('#portfolio-display').html();
    
    var teamsScript = Handlebars.compile(teamsTemplate);
    var teamsHtml = teamsScript(context);
    
    $(document.body).append(teamsHtml);
    $( "#accordion" ).accordion({heightStyle: "content",
                                collapsible: true});

    
}